### ISSUE TITLE
i would like to know how to implement the older colors of ogar

### ISSUE THREAD

**Issue by Agarian** [ItzLevvie/Ogar#4]
i want to know this simply for personal use. *mainly because I like the older colors better.*
**current function for colors:** GameServer.prototype.getRandomColor=function(){var e=Math.floor(3 * Math.random());return 0==e?{r:255,b:255 * Math.random(),g:0}:1==e?{r:0,b:255,g:255 * Math.random()}:{r:255 * Math.random(),b:0,g:255}}

**the old colors:**

        {'r':235, 'g': 75, 'b':  0},

        {'r':225, 'g':125, 'b':255},

        {'r':180, 'g':  7, 'b': 20},

        {'r': 80, 'g':170, 'b':240},

        {'r':180, 'g': 90, 'b':135},

        {'r':195, 'g':240, 'b':  0},

        {'r':150, 'g': 18, 'b':255},

        {'r': 80, 'g':245, 'b':  0},

        {'r':165, 'g': 25, 'b':  0},

        {'r': 80, 'g':145, 'b':  0},
 
        {'r': 80, 'g':170, 'b':240},

        {'r': 55, 'g': 92, 'b':255},

**old color function:** var index = Math.floor(Math.random() * this.colors.length);    var color = this.colors[index];     return {         r: color.r,         b: color.b,         g: color.g    };

Whenever attempting to add these, it always gives 'unexpected token' errors.

**Comment by ItzLevvie** [comment]
```
    this.colors = [
      {'r': 235,'g': 75,'b': 0},
      {'r': 225,'g': 125,'b': 255},
      {'r': 180,'g': 7,'b': 20},
      {'r': 80,'g': 170,'b': 240},
      {'r': 180,'g': 90,'b': 135},
      {'r': 195,'g': 240,'b': 0},
      {'r': 150,'g': 18,'b': 255},
      {'r': 80,'g': 245,'b': 0},
      {'r': 165,'g': 25,'b': 0},
      {'r': 80,'g': 145,'b': 0},
      {'r': 80,'g': 170,'b': 240}, 
      {'r': 55,'g': 92,'b': 255},
    ];
};
```
and
```
GameServer.prototype.getRandomColor = function() {
    var index = Math.floor(Math.random() * this.colors.length);
    var color = this.colors[index];
    return {
        r: color.r,
        b: color.b,
        g: color.g
    };
};
```

**Comment by Agarian** [comment]
what about them?

**Comment by Agarian** [comment]
posting the functions does not help.

**Comment by Agarian** [comment]
ok den

**Comment by Agarian** [comment]
actually no longer a need. i was lucky to have an older build of this dev that had the old code format(like in the regular ogar). so it was easy then.
